Repository thalees/serveless-studies-api, pull requests merged in 2020-06, with the labels that each got.

#4 Book Handler
  .gitignore
  .idea/.gitignore
  .idea/artifacts/serveless_studies_api_jar.xml
  .idea/compiler.xml
  .idea/jarRepositories.xml
  .idea/misc.xml
  .idea/vcs.xml
  build.gradle
  src/main/java/br/com/studiesMaterials/dao/BookDao.java
  src/main/java/br/com/studiesMaterials/domain/Book.java
  src/main/java/br/com/studiesMaterials/handlers/BookHandler.java
  src/main/java/br/com/studiesMaterials/web/api/schemas/BookResponse.java
  src/main/java/br/com/studiesMaterials/web/api/schemas/BookSchema.java
Labels: good first issue

#1 Podcast handler
  src/main/java/br/com/studiesMaterials/dao/PodcastDao.java
  src/main/java/br/com/studiesMaterials/handlers/PodcastHandler.java
  src/main/java/br/com/studiesMaterials/web/api/schemas/PodcastResponse.java
  src/main/java/br/com/studiesMaterials/web/api/schemas/PodcastSchema.java
Labels: enhancement

#3 Student handler
  build.gradle
  src/main/java/br/com/studiesMaterials/dao/StudentDao.java
  src/main/java/br/com/studiesMaterials/handlers/BookHandler.java
  src/main/java/br/com/studiesMaterials/handlers/CourseHandler.java
  src/main/java/br/com/studiesMaterials/handlers/PodcastHandler.java
  src/main/java/br/com/studiesMaterials/handlers/StudentHandler.java
  src/main/java/br/com/studiesMaterials/web/api/responses/ArticleResponse.java
  src/main/java/br/com/studiesMaterials/web/api/responses/BookResponse.java
  src/main/java/br/com/studiesMaterials/web/api/responses/CourseResponse.java
  src/main/java/br/com/studiesMaterials/web/api/responses/PodcastResponse.java
  src/main/java/br/com/studiesMaterials/web/api/responses/StudentResponse.java
  src/main/java/br/com/studiesMaterials/web/api/schemas/ArticleResponse.java
  src/main/java/br/com/studiesMaterials/web/api/schemas/BookResponse.java
  src/main/java/br/com/studiesMaterials/web/api/schemas/BookSchema.java
  src/main/java/br/com/studiesMaterials/web/api/schemas/CourseResponse.java
  src/main/java/br/com/studiesMaterials/web/api/schemas/PodcastResponse.java
  src/main/java/br/com/studiesMaterials/web/api/schemas/PodcastSchema.java
  src/main/java/br/com/studiesMaterials/web/api/schemas/StudentSchema.java
Labels: enhancement

#5 Documentation
  README.md
Labels: documentation
